config/routes.rb
Rails.application.routes.draw do

  post 'pay2go/return'
  post 'pay2go/notify'
  
  get "/react" => "welcome#react"
  get "/vue" => "welcome#vue"

  resources :products do
    member do
      post :add_to_cart
      post :remove
    end
  end

  resources :orders do
    member do
       post :checkout_pay2go
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :ubikes

  resources :topics do
    member do
      post :like
      post :unlike
    end

    #resources :likes
  end

  namespace :admin do
    resources :products # Admin::ProductsController
  end

  root "products#index"
end

app/models/topic.rb
class Topic < ApplicationRecord

  validates_presence_of :title

  belongs_to :user, :optional => true

  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, :source => :user

  def find_like(user)
    Like.where( :topic_id => self.id, :user_id => user.id ).first
  end

  def is_liked_by(user)
    user && find_like(user).present?
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.order("id DESC")
  end

  def create
    @topic = Topic.create( topic_params )
    @topic.user = current_user
    @topic.save

    respond_to do |format|
      format.js # create.js.erb
      format.html { redirect_to topics_path }
    end
  end

  def like
    @topic = Topic.find( params[:id] )

    unless @topic.is_liked_by(current_user)
      Like.create( :topic => @topic, :user => current_user )
    end

    respond_to do |format|
      format.js
      format.html { redirect_to topics_path }
    end
  end

  def unlike
    @topic = Topic.find(params[:id])
    like = @topic.find_like(current_user)

    like.destroy

    respond_to do |format|
      format.js { render "like" } # like.js.erb
      format.html { redirect_to topics_path }
    end
  end

  def destroy
    @topic = Topic.find( params[:id] )
    @topic.destroy

    respond_to do |format|
      # :remote => true
      format.js # destroy.js.erb
      format.html { redirect_to topics_path }
    end
  end

  protected

  def topic_params
    params.require(:topic).permit(:title)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_like.html.erb
<% topic.liked_users.each do |u| %>
  <%= u.display_name %>,
<% end %>

<% if topic.is_liked_by(current_user) %>
  <%= link_to "-1", unlike_topic_path(topic), :method => :post, :class => "btn btn-primary", :remote => true %>
<% else %>
  <%= link_to "+1", like_topic_path(topic), :method => :post, :class => "btn btn-success", :remote => true %>
<% end %>

app/views/topics/_tr.html.erb
<tr id="topic-<%= topic.id %>">
  <td><%= topic.title %></td>
  <td id="topic-like-count-<%= topic.id %>">
    <%= topic.liked_users.size %>
  </td>
  <td id="topic-like-<%= topic.id %>">
    <%= render :partial => "like", :locals => { :topic => topic } %>
  </td>
  <td>
    <%= link_to "Delete", topic_path(topic), :method => :delete, :remote => true, :class => "btn btn-danger" %>
  </td>
</tr>

app/views/topics/create.js.erb
<% if @topic.valid? %>
  str = "<%= j render :partial => "tr", :locals => { :topic => @topic } %>";
  $("table").prepend(str);
  $("#topic_title").val("");

<% else %>

  alert("GG");

<% end %>

app/views/topics/destroy.js.erb
$("#topic-<%= @topic.id %>").remove();


$("#topics-count").text(<%= Topic.count %>);

app/views/topics/index.html.erb
<h1>Topics list (<span id="topics-count"><%= Topic.count %></span>)</h1>

<%= form_for Topic.new, :remote => true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "新增", :class => "btn btn-primary" %>
  </div>
<% end %>


<table class="table">
<% @topics.each do |topic| %>
  <%= render :partial => "tr", :locals => { :topic => topic } %>
<% end %>
</table>

app/views/topics/like.js.erb
str = "<%=j render :partial => "like", :locals => { :topic => @topic } %>"

$("#topic-like-<%= @topic.id %>").html(str);

$("#topic-like-count-<%= @topic.id %>").text( <%= @topic.liked_users.count %> );

app/views/topics/unlike.js.erb
alert("OK unlike");