config/routes.rb
Rails.application.routes.draw do

  post 'pay2go/return'
  post 'pay2go/notify'
  
  get "/react" => "welcome#react"
  get "/vue" => "welcome#vue"

  resources :products do
    member do
      post :add_to_cart
      post :remove
    end
  end

  resources :orders do
    member do
       post :checkout_pay2go
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :ubikes

  resources :topics do
    member do
      post :like
      post :unlike
    end

    #resources :likes
  end

  namespace :admin do
    resources :products # Admin::ProductsController
  end

  root "products#index"
end

app/models/order.rb
class Order < ApplicationRecord

  validates_presence_of :name

  belongs_to :user

  has_many :order_items

  has_many :payments

  def paid?
    self.status == "paid"
  end

  def add_items(cart)
    cart.cart_items.each do |item|
      self.order_items.build( :product_id => item.product_id,
                              :qty => item.qty,
                              :price => item.product.price )
    end

    self.amount = self.order_items.map{ |i| i.qty * i.price }.sum
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  def index
    @orders = current_user.orders.order("id DESC")
  end

  def new
    if current_cart.cart_items.empty?
      flash[:alert] = "沒東西幹嘛結帳!!"
      redirect_to root_path
    end

    @order = Order.new
  end

  def create
    @order = Order.new( order_params )
    @order.user = current_user
    @order.add_items(current_cart)

    if @order.save
      UserMailer.notify_order(@order).deliver_later

      current_cart.destroy
      session[:cart_id] = nil

      redirect_to order_path(@order)
    else
      render "new"
    end
  end

  def show
    @order = current_user.orders.find( params[:id] )
  end

  def checkout_pay2go
    @order = current_user.orders.find( params[:id] )

    if @order.paid?
      flash[:alert] = "你已經付過啦"
      redirecto_to order_path(@order)
    else
      @payment = Payment.create!( :order => @order,
                                  :payment_method => params[:payment_method],
                                  :amount => @order.amount )
      render :layout => false
    end
  end

  protected

  def order_params
    params.require(:order).permit(:name, :phone, :address, :payment_method, :shipping_method)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper

    def generate_pay2go_params(payment)
        pay2go_params = {
          MerchantID: Pay2go.merchant_id,
          RespondType: "JSON",
          TimeStamp: payment.created_at.to_i,
          Version: "1.2",
          LangType: "en", # I18n.locale.downcase, # zh-tw or en
          MerchantOrderNo: payment.external_id,
          Amt: payment.amount,
          ItemDesc: payment.name,
          ReturnURL: pay2go_return_url,
          NotifyURL: Pay2go.notify_url,
          Email: payment.email,
          LoginType: 0,
          CREDIT: 0,
          WEBATM: 0,
          VACC: 0,
          CVS: 0,
          BARCODE: 0
        }

        case payment.payment_method
          when "Credit"
            pay2go_params.merge!( :CREDIT => 1 )
          when "WebATM"
            pay2go_params.merge!( :WEBATM => 1 )
          when "ATM"
            pay2go_params.merge!( :VACC => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
          when "CVS"
            pay2go_params.merge!( :CVS => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
          when "BARCODE"
            pay2go_params.merge!( :BARCODE => 1, :ExpireDate => payment.deadline.strftime("%Y%m%d") )
        end

        pay2go = Pay2go.new(pay2go_params)
        pay2go_params[:CheckValue] = pay2go.make_check_value
        pay2go_params
    end

end

app/views/orders/checkout_pay2go.html.erb
<h1>轉址前往信用卡付款頁面，請勿關閉或離開頁面...</h1>

<form action="<%= Pay2go.url %>" method="post">

  <% generate_pay2go_params(@payment).each do |key, value| %>
    <%= hidden_field_tag key, value %>
  <% end %>

  <input type="submit" style="visibility:hidden;">
</form>

<script>document.forms[0].submit()</script>

app/views/orders/index.html.erb
<h1>我的訂單</h1>

<table class="table">
<% @orders.each do |order| %>
<tr>
  <td><%= link_to order.id, order_path(order) %></td>
  <td><%= order.name %></td>
  <td><%= order.phone %></td>
  <td>$<%= order.amount %></td>
  <td>
    <ul>
    <% order.order_items.each do |i| %>
      <li><%= i.product.name %>
        $<%= i.price %> x <%= i.qty %></li>
    <% end %>
    </ul>
  </td>
</tr>
<% end %>
</table>

app/views/orders/new.html.erb
<ul>
<% current_cart.cart_items.each do |item| %>
  <li>
    <%= item.product.name %> 數量<%= item.qty %>
    <%= link_to "不買了!", remove_product_path(item.product), :method => :post, :class => "btn btn-danger btn-sm" %>
  </li>
<% end %>
</ul>

<%= @order.errors.full_messages %>

<%= form_for @order do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :payment_method %>
    <%= f.select :payment_method, [ ["信用卡", "credit_card"], ["ATM轉帳", "atm"]] , :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/show.html.erb
<h1>訂單編號 <%= @order.id %></h1>

<p>訂單狀態: <%= t( @order.status, :scope => "order.status" ) %></p>
<p>付款方式: <%= t( @order.payment_method ) %></p>
<p>Amount: <%= @order.amount %></p>

<% @order.order_items.each do |item| %>
  <li><%= item.product.name %> 數量<%= item.qty %></li>
<% end %>
<hr>

<% if @order.status == "new" %>

<p>
  <% Payment::PAYMENT_METHODS.each do |pm| %>
    <%= link_to t(pm, :scope => "PaymentPay2go"), checkout_pay2go_order_path(@order, :payment_method => pm), :class => "btn btn-primary btn-lg", :method => :post %>
  <% end %>
</p>

<% end %>