config/routes.rb
Rails.application.routes.draw do

  post 'pay2go/return'
  post 'pay2go/notify'
  
  get "/react" => "welcome#react"
  get "/vue" => "welcome#vue"

  resources :products do
    member do
      post :add_to_cart
      post :remove
    end
  end

  resources :orders do
    member do
       post :checkout_pay2go
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :ubikes

  resources :topics do
    member do
      post :like
      post :unlike
    end

    #resources :likes
  end

  namespace :admin do
    resources :products # Admin::ProductsController
  end

  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin!

  def index
    @products = Product.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find( params[:id] )

    current_cart.add_product(@product)

    #redirect_to root_path

  end

  def remove
    @product = Product.find(params[:id])

    existing_item = current_cart.cart_items.where( :product_id => @product.id ).first
    existing_item.destroy

    redirect_to :back
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/add_to_cart.js.erb
$("#cart-total").text(<%= current_cart.total_qty %>);

app/views/products/index.html.erb
<h1><%= t( "product_list" ) %></h1>

<p>購物車有<span id="cart-total"><%= current_cart.total_qty %></span>個商品</p>

<hr>
<% @products.each do |product| %>
<div class="product">
  <%= link_to product_path(product) do %>
    <%= image_tag(product.image_url, :width => 120) %>
    <p>
      <%= product.name %>
      $<%= product.price %>
    </p>
    <p>
      <%= link_to "加入購物車", add_to_cart_product_path(product), :method => :post, :class => "btn btn-primary", :remote => true %>
    </p>
  <% end %>
</div>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= image_tag(@product.image_url) %>

上架時間: <%= @product.created_at %>

<%= simple_format @product.description %>